### ISSUE TITLE
No data available for the specified years or type. Please check your user name! 

### ISSUE THREAD

**Issue by BarryYangi** [yihong0618/GitHubPoster#100]
Run python -m github_poster github --github_user_name *** --me *** --with-animation --stand-with-ukraine

现在怎么拿不到GitHub的数据了

**Comment by yihong0618** [comment]
我们看看

**Comment by yihong0618** [comment]
@BarryYangi 修复了，拉下最新代码再试试？

**Comment by imnxg** [comment]
Run python3 -m github_poster wakatime --wakatime_key "***" --me ***
也拿不到数据

**Comment by yihong0618** [comment]
@imnxg  我很久没用了，可能过段时间看看
如果你解决了 PR welcome

**Comment by imnxg** [comment]
@yihong0618 好
