### ISSUE TITLE
Garmin登陆似乎有问题

### ISSUE THREAD

**Issue by ICYMYM** [yihong0618/GitHubPoster#103]
![image](https://github.com/yihong0618/GitHubPoster/assets/3919539/f8c64ca2-ce0b-4236-a40c-a3571d06a772)

python3 -m github_poster garmin --garmin_user_name 'xxx' --garmin_password 'xxxx' --year 2022-2023 --special-color1 blue --special-color2 pink --me xxx --cn

**Comment by yihong0618** [comment]
是的，你可以先用 running_page 的 garmin, 我稍后更新下。
https://github.com/yihong0618/running_page

**Comment by yihong0618** [comment]
@ICYMYM pip install -U garminconnect
