### ISSUE TITLE
微信读书，使用同样的参数配置，在本地可以运行并成功生成SVG，但是action失败。

### ISSUE THREAD

**Issue by KevinChen1994** [yihong0618/GitHubPoster#108]
多谢大佬的项目，很好用！

最近action一直在报错，Exception: Can not get weread history data。我怀疑是cookie过期导致的，所以我重新上传了cookie，但是运行后还是同样的错误。
于是我在本地debug了一遍，在获取微信读书数据时能够成功获取，并且生成了SVG图片，我看图片的数据时最新的也没有问题。
这种线上和线下不一致是怎么导致的呢？

谢谢。

**Comment by yihong0618** [comment]
actions 应该是会过期
本地成功 actions 不成功的话大概率是 cookie 格式问题。
微信读书不建议用 actions...

**Comment by yihong0618** [comment]
过期只能更新，我不确定微信读书的过期时间。

你 action secret 和本地用的是一个 cookie 么？如果是，secret 里的没放引号之类的东西吧？

**Comment by KevinChen1994** [comment]
是同一个cookie，没有带引号。
本地运行因为是参数问题所以需要加上引号，但是在github上的配置是没有引号的。

**Comment by KevinChen1994** [comment]
问题解决了，在配置里填写微信读书的cookie时加上引号就好了。
具体原因我不清楚为什么，之前貌似是不加引号的。

**Comment by yihong0618** [comment]
好的
