### ISSUE TITLE
[feature] Generate Wakatime poster?

### ISSUE THREAD

**Issue by JasonkayZK** [yihong0618/GitHubPoster#11]
Greatest poster generator ever!

WakaTime is a widget that can be embedded into lots of IDEs to track coding time.

Here is a report page demo:

![WakaTime report](https://user-images.githubusercontent.com/40811521/121992431-37ed6e00-cdd4-11eb-8267-ca7431c792c0.png)

And the corresponding API Doc:

- [WakaTime Doc](https://wakatime.com/developers)

So i'm wondering if there is any chances generating the WakaTime's poster? 

Thanks a lot!

**Comment by yihong0618** [comment]
@JasonkayZK 
I have not used waka time for a longtime, and seems that must a pro user can get all the history data?

Do you have interest to open `PR` for that? 
just add new `loader` is ok.

**Comment by JasonkayZK** [comment]
I give it a try~

**Comment by yihong0618** [comment]
inherit the `BaseLoader` then impl these two method
```python
    @abstractmethod
    def make_track_dict(self):
        pass

    @abstractmethod
    def get_all_track_data(self):
        pass
```

**Comment by yihong0618** [comment]
@JasonkayZK 
Can you add wakatime `svg` in examples files too?

**Comment by JasonkayZK** [comment]
OK, I generate mine to add.
