### ISSUE TITLE
SVG title username 如果可以自动获取，那就更棒了

### ISSUE THREAD

**Issue by ThaddeusJiang** [yihong0618/GitHubPoster#2]
例如：

我的 Twitter https://twitter.com/ThaddeusJiang

ID: ThaddeusJiang
name: TJ

现状：

* default: Joey
* or `--name TJ`

期待：

* default: TJ
* 可以通过 `--name` 覆盖

![image](https://user-images.githubusercontent.com/17308201/117559263-bf054300-b0be-11eb-8bdc-90b974684594.png)

**Comment by yihong0618** [comment]
好嘞，明天我加一下

**Comment by yihong0618** [comment]
@ThaddeusJiang 想了下，好像不太行，因为这个获取是靠 id_name 而大部分人的展示的 user_name 和 id_name 不太一致，我再试试。
