### ISSUE TITLE
Skyline 模型能否带上用户名？

### ISSUE THREAD

**Issue by MamaShip** [yihong0618/GitHubPoster#21]
将 `--me` 参数传入的用户名称一起生成在模型底座上，放在靠左或靠右的位置都可以。

![示意图](https://user-images.githubusercontent.com/7104870/124058707-79c91600-da5c-11eb-9a63-24edcd81f21a.png)

**Comment by yihong0618** [comment]
@MamaShip 

我之前想加来的，还可以把 data 加上。
我找时间加一下。

如果你有兴趣提个 `PR`, 加上这个，always welcome~
 
note: 但需要 assert 下长度，要不容易出去。

**Comment by MamaShip** [comment]
> 
> 
> @MamaShip
> 
> 我之前想加来的，还可以把 data 加上。
> 我找时间加一下。
> 
> 如果你有兴趣提个 `PR`, 加上这个，always welcome~
> 
> note: 但需要 assert 下长度，要不容易出去。

好的，我研究一下提个 PR。以可选参数的方式供用户选择

**Comment by yihong0618** [comment]
代码位置，需要计算下 offset, 我有些代码是 hardcode 的，如果造成困扰，抱歉~~^_^

https://github.com/yihong0618/GitHubPoster/blob/e5be7103c259434e4c89bd4370678b4bc854fc96/skyline/skyline.py#L69
