### ISSUE TITLE
能否生成多个issue

### ISSUE THREAD

**Issue by Daydog** [yihong0618/GitHubPoster#32]
比如我有一个俯卧撑的issue，还有一个游泳的issue，还有早睡issue， 能否生成 “两个/多个” 统计
我在代码里面加了一行 同样 的post issue 代码， 但是覆盖了之前的issue svg, 没有生成两个issue svg

**Comment by yihong0618** [comment]
嗯，目前只支持一个，但可以修改下，我之后看一下。

**Comment by yihong0618** [comment]
@Daydog 可以拉最新代码试一下，目前没传 pypi, pip 方式可能不好用

**Comment by Daydog** [comment]
> @Daydog 可以拉最新代码试一下，目前没传 pypi, pip 方式可能不好用

感谢，我测试了一个成功了, 这个可以发挥的作用更大了，可以自定义添加多个
使用方法：
```
      - name: Run sync issue script
        if: contains(env.TYPE, 'issue')
        run: |
          python -m github_poster issue --issue_number ${{ secrets.ISSUE_NUMBER }} --repo_name ${{ secrets.REPO_NAME }} --github_token ${{ secrets.G_T }} --me ${{ env.ME }}
          
      - name: Run sync issue2 script
        if: contains(env.TYPE, 'issue')
        run: |
          python -m github_poster issue --issue_number ${{ secrets.ISSUE_NUMBER2 }} --repo_name ${{ secrets.REPO_NAME }} --github_token ${{ secrets.G_T }} --me ${{ env.ME }}
```

这里想多问个仓库 “2021”的问题, 我在2021/daily/config.py 里面添加如下代码，会自动在readme “我的数字” 区多显示一行吗，如果不显示，请问还需要改什么地方

```
ENGLISH_LABEL_LIST = [
    "English",
]
```

**Comment by yihong0618** [comment]
@Daydog 
这里也需要加

https://github.com/yihong0618/2021/blob/main/daily/utils.py#L162-#L669
