### ISSUE TITLE
[Leetcode-CN] sometimes it sends me a wierd permission error

### ISSUE THREAD

**Issue by underwindfall** [yihong0618/GitHubPoster#33]
# Context
Basically, I just launch this command to generate a leetcode svg
```
python3 -m github_poster leetcode --leetcode_cookie xxx --cn 
```
I'm sure about the cookie is correct.

# What I got
The output command line it shows me as a result of 
![image](https://user-images.githubusercontent.com/14819756/136147259-3b9347f4-6c92-4837-b273-4fefc55bc101.png)

# Solution I may find
So I dig into your code, I increase the time duration to `2 seconds` of [this line](https://github.com/yihong0618/GitHubPoster/blob/main/github_poster/loader/leetcode_loader.py#L67) 

it turns out everything is great.

I wonder if there is another way to get througth it ?

----
BTW, great work 🎆 🎆 🎆 👍 !!!!

**Comment by yihong0618** [comment]
Got it. maybe they increase the api call limit. Can you open a PR using your way (^-^)

**Comment by underwindfall** [comment]
@yihong0618 sure https://github.com/yihong0618/GitHubPoster/pull/34
