### ISSUE TITLE
Support Chinese name

### ISSUE THREAD

**Issue by jingchangshi** [yihong0618/GitHubPoster#38]
Please add an option to change the font used to render the name.
Otherwise the default Arial font does not support the Chinese name. The name is rendered as squares.
The relevant codes are as follows,

```
    def __draw_header(self, d):
        text_color = self.colors["text"]
        #  title_style = "font-size:12px; font-family:Arial; font-weight:bold;"
        title_style = "font-size:12px; font-family:'Inziu Iosevka SC'; font-weight:bold;"
        d.add(d.text(self.title, insert=(10, 20), fill=text_color, style=title_style))
```

**Comment by yihong0618** [comment]
will do it maybe Monday or do you have interest to open a PR to support that thanks

**Comment by yihong0618** [comment]
Done use --font to support
