### ISSUE TITLE
添加数据持久化支持

### ISSUE THREAD

**Issue by Zxilly** [yihong0618/GitHubPoster#44]
我希望给这个项目添加 `不背单词` 的支持，但是他们的API是只支持查询最近一个月的数据，需要数据的持久化。
同时我希望给这个项目添加 SaaS 支持，即允许其本身作为一个服务器返回生成好的 svg。
不知道您的看法如何？

**Comment by yihong0618** [comment]
可以的，pr always welcome.

**Comment by yihong0618** [comment]
> 我希望给这个项目添加 `不背单词` 的支持，但是他们的API是只支持查询最近一个月的数据，需要数据的持久化。 同时我希望给这个项目添加 SaaS 支持，即允许其本身作为一个服务器返回生成好的 svg。 不知道您的看法如何？

但请注意，我之前一直没弄的原因是好多 poster 需要填写账号密码，这个对安全不太友好，所以一直没弄。

**Comment by Zxilly** [comment]
@yihong0618 我的想法是搭建自用，因为如果需要数据持久化，依靠CI可能就比较麻烦

**Comment by yihong0618** [comment]
> @yihong0618 我的想法是搭建自用，因为如果需要数据持久化，依靠CI可能就比较麻烦，即token仍然是自行维护

嗯嗯，我另一个项目 running_page 做持久化用的是 sqllite, 用户 fork 自行维护。
https://github.com/yihong0618/running_page
