### ISSUE TITLE
generating duolingo poster failed

### ISSUE THREAD

**Issue by dexhunter** [yihong0618/GitHubPoster#5]
I met this error when generating poster for duolingo

![image](https://user-images.githubusercontent.com/6930518/120455506-68daa580-c3c7-11eb-9e7b-a1a188577057.png)

```
File "/home/<user>/GitHubPoster/loader/base_loader.py", line 29, in <listcomp>
month_list = [m for m in month_list if m < pendulum.now()]  
```

```
ValueError: Posix spec does not match last transition     
```

I think we need to check if the timezone matches?

**Comment by yihong0618** [comment]
Will take a look later.

**Comment by dexhunter** [comment]
ok, I found the problem was caused by calling `pendulum.now()` on [this line](https://github.com/yihong0618/GitHubPoster/blob/main/loader/base_loader.py#L29) after commenting the line, the problem was solved, but anyways I think we can add timezone info on the settings since you already hardcoded timezone info on the config

**Comment by yihong0618** [comment]
Yes, I think that would be fine. Early I thought it is only for Chinese +8 timezone, So I hardcode it.
Do you have interest open a `PR`

**Comment by yihong0618** [comment]
> ok, I found the problem was caused by calling `pendulum.now()` on [this line](https://github.com/yihong0618/GitHubPoster/blob/main/loader/base_loader.py#L29) after commenting the line, the problem was solved, but anyways I think we can add timezone info on the settings since you already hardcoded timezone info on the config
> 
> P.S or delete the hardcoded timezone info as I didn't see a difference after removing it

No difference for comment that line, Just we do not need to get the data after `Today`. So I filtered it

**Comment by yihong0618** [comment]
@dexhunter 
![image](https://user-images.githubusercontent.com/15976103/120461364-878f6b00-c3cc-11eb-8637-963726572619.png)

Just tests and no errors for me.
Maybe windows problem or something else, I will look into it.

**Comment by yihong0618** [comment]
Btw, I am thinking of changing to another API, because this only have `log data`.

see
https://web.shanbay.com/web/wechat/calendar/?user_id=${id}

but this api will be slow.

**Comment by dexhunter** [comment]
ok thanks for the reply, another problem I found is that the result seems not matching to my real profile. I am on a 173-day-streak while the generated poster does not figure out most of my activities.
![image](https://user-images.githubusercontent.com/6930518/120468009-549ca580-c3d3-11eb-9e5b-ccb4d1590e7a.png)

genereated ones

![image](https://user-images.githubusercontent.com/6930518/120468317-a6453000-c3d3-11eb-9b8b-ae4c81161a57.png)

**Comment by dexhunter** [comment]
I also checked [the xp summary](https://www.duolingo.com/2017-06-30/users/15242908/xp_summaries?language=Japanese) but the result seems not right as well, so I think the problem is on the api_endpoint

**Comment by dexhunter** [comment]
I think we can consider to use something like  `https://www.duolingo.com/2017-06-30/users/<user>?fields=xpGains&endDate=2021-05-03&startDate=2021-01-01`

**Comment by yihong0618** [comment]
Checking it now.

**Comment by yihong0618** [comment]
works fine for me.
Can you make sure this is the `duolingo_user_name`

![image](https://user-images.githubusercontent.com/15976103/120471400-40f33e00-c3d7-11eb-81e1-d20f0fafd338.png)

![Uploading image.png…]()

**Comment by dexhunter** [comment]
Yep I think the id is right, I think the problem is that it counts on a different language (I am currently learning multiple languages)
![image](https://user-images.githubusercontent.com/6930518/120471755-af380080-c3d7-11eb-915d-83c2900a56cd.png)

**Comment by dexhunter** [comment]
but it doesn't help when I set language as seen in  `https://www.duolingo.com/2017-06-30/users/15242908/xp_summaries?language=Japanese`

**Comment by yihong0618** [comment]
Ah got it, can you change your learning lanaguage in `duolingo side`.  Change the default one?

**Comment by dexhunter** [comment]
The current default one should already be the Japanese but I am not sure how the API works

**Comment by yihong0618** [comment]
https://www.duolingo.com/2017-06-30/users/{your_id}/xp_summaries?endDate=2021-02-01&startDate=2021-01-01&timezone=Asia/Shanghai

**Comment by yihong0618** [comment]
> [https://www.duolingo.com/2017-06-30/users/{your_id}/xp_summaries?endDate=2021-02-01&startDate=2021-01-01&timezone=Asia/Shanghai](https://www.duolingo.com/2017-06-30/users/%7Byour_id%7D/xp_summaries?endDate=2021-02-01&startDate=2021-01-01&timezone=Asia/Shanghai)

@dexhunter just call this in the browser

**Comment by dexhunter** [comment]
![image](https://user-images.githubusercontent.com/6930518/120472666-c0354180-c3d8-11eb-8a3c-4bae8a17b7d0.png)

I only see one setting though

**Comment by yihong0618** [comment]
@dexhunter I just make it for you, it works........ using your duolingo_user_name 

Is it yours?
![image](https://user-images.githubusercontent.com/15976103/120472801-eb1f9580-c3d8-11eb-9d04-b21703288c28.png)

![image](https://user-images.githubusercontent.com/15976103/120472866-0094bf80-c3d9-11eb-9234-d7880078a320.png)

**Comment by yihong0618** [comment]
Do you think its the timezone problem??
It works in my side.

**Comment by dexhunter** [comment]
hmm...okay, weird, yep it might caused by the datetime info

**Comment by dexhunter** [comment]
in that case, it might be caused by my computer settings, anyways thanks for the help, I am closing the issue for now

**Comment by yihong0618** [comment]
Can you use `GitHub Actions` to generate it ? Maybe its your timezone problem
It maybe right.
Just set the secret.
![image](https://user-images.githubusercontent.com/15976103/120473310-79941700-c3d9-11eb-8891-6dd585170acf.png)

**Comment by yihong0618** [comment]
Change it to yours. And the `svg` will generate in the `OUT_FOLDER`
![image](https://user-images.githubusercontent.com/15976103/120473431-992b3f80-c3d9-11eb-8ab6-90ad45f35726.png)

**Comment by dexhunter** [comment]
Yep, thanks, got my results [there](https://github.com/dexhunter/GitHubPoster/blob/main/OUT_FOLDER/duolingo.svg)

**Comment by yihong0618** [comment]
Seems that the timezone on your computer the `pendulm` pendulum can not parse.
https://stackoverflow.com/questions/55801582/how-to-fix-valueerror-time-date-does-not-match-format-when-converting-from-strin

**Comment by yihong0618** [comment]
@dexhunter 大陆地区（可能包括 hk）的多邻国不再好用了。

参考这几条推。https://twitter.com/yihong0618/status/1432142636593270784

https://twitter.com/yihong0618/status/1431481350855413765

**Comment by dexhunter** [comment]
Thanks, I'll check it out.
