### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by sun0225SUN** [yihong0618/GitHubPoster#50]
我执行了actions，也添加了相应的secrets，actions正常触发没有报错，但是并没有commit数据。
![2022-01-30_14-35-20](https://user-images.githubusercontent.com/79169717/151689538-3be44ae2-8646-4c11-bf22-8ebf747d1779.jpg)
我觉着`svg`应该是正常生成了吧，可能提交的文件路径需要我设置下，我不太清楚怎么解决这个问题。
如果大佬有时间的话，可以帮我看下么，万分感谢！
![2022-01-30_14-41-39](https://user-images.githubusercontent.com/79169717/151689589-b5a4f00b-6985-4632-8ef2-ed504c4d2431.jpg)

**Comment by yihong0618** [comment]
看了下你好像把 OUT_FOLDER 删了，正常你跑出来的 poster 会存在这里

**Comment by sun0225SUN** [comment]
好哒好哒，我才发现那俩文件夹没了，我试下，大佬太帅了哇，respect！❤️

**Comment by sun0225SUN** [comment]
> 看了下你好像把 OUT_FOLDER 删了，正常你跑出来的 poster 会存在这里

大佬，我不太懂`.gitignore`的作用，我第一次没您说的`OUT_FOLDER`文件夹就是因为 git 把他忽略了，然后 GitHub actions 也commit不了数据。😲

而且在Windows上，`.gitignore`这个文件是隐藏的，我折腾了好大会儿，才想起来为啥我`commit`不了这几个文件夹🤕

![2022-01-30_17-04-04](https://user-images.githubusercontent.com/79169717/151694019-24b92b17-5fab-466e-a014-4a3f1904a6d3.jpg)

我把这个文件删了，然后重新部署了下，一切很完美🎉

<b>大佬真的太帅了，我也要好好学习，像你一样做一些有意义的项目。🥳</b>

![2022-01-30_17-24-26](https://user-images.githubusercontent.com/79169717/151694095-3989ceed-0eb6-456c-bf06-f7e4ae8a506a.jpg)

**Comment by yihong0618** [comment]
> > 看了下你好像把 OUT_FOLDER 删了，正常你跑出来的 poster 会存在这里
> 
> 
> 
> 大佬，我不太懂`.gitignore`的作用，我第一次没您说的`OUT_FOLDER`文件夹就是因为 git 把他忽略了，然后 GitHub actions 也commit不了数据。😲
> 
> 
> 
> 而且在Windows上，`.gitignore`这个文件是隐藏的，我折腾了好大会儿，才想起来为啥我`commit`不了这几个文件夹🤕
> 
> 
> 
> ![2022-01-30_17-04-04](https://user-images.githubusercontent.com/79169717/151694019-24b92b17-5fab-466e-a014-4a3f1904a6d3.jpg)
> 
> 
> 
> 我把这个文件删了，然后重新部署了下，一切很完美🎉
> 
> 
> 
> <b>大佬真的太帅了，我也要好好学习，像你一样做一些有意义的项目。🥳</b>
> 
> 
> 
> ![2022-01-30_17-24-26](https://user-images.githubusercontent.com/79169717/151694095-3989ceed-0eb6-456c-bf06-f7e4ae8a506a.jpg)
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

过誉了哈哈，谢谢你喜欢
