### ISSUE TITLE
issue没有成功生成svg

### ISSUE THREAD

**Issue by goldenages1989** [yihong0618/GitHubPoster#51]
用我自己仓库的issue生成的是空白的svg文件
![image.png](https://s2.loli.net/2022/02/03/XVTk4tsAGPcFQ5j.png)
用了您仓库的issue也是同样的问题，请问可能是哪的配置有问题吗？
命令: `github_poster issue --issue_number 12 --repo_name yihong0618/2021 --year=2021`

**Comment by yihong0618** [comment]
@goldenages1989 
Hi~
这个需要 issue 里面有内容的，做的是 sum 和读取第一行，
可以参考我这个 issue

https://github.com/yihong0618/2022/issues/2

**Comment by goldenages1989** [comment]
嗯嗯，我配置的issue里面也是有内容的
但是action执行完后没有没有取到
https://github.com/goldenages1989/2022/issues/1

**Comment by yihong0618** [comment]
> 嗯嗯，我配置的issue里面也是有内容的
> 
> 但是action执行完后没有没有取到
> 
> https://github.com/goldenages1989/2022/issues/1

我看下～

**Comment by yihong0618** [comment]
@goldenages1989 
因为用的不同逻辑，你需要把最后一行 改成 return 1 或者自己 DIY 一下。
这个取的是 int(data) 因为你记得是早起，所以取不到。

https://github.com/yihong0618/GitHubPoster/blob/248d0c8f998e75d1c9d198c47230f40ec2975b3c/github_poster/loader/from_github_issue_loader.py#L40-L45

**Comment by goldenages1989** [comment]
> @goldenages1989 因为用的不同逻辑，你需要把最后一行 改成 return 1 或者自己 DIY 一下。 这个取的是 int(data) 因为你记得是早起，所以取不到。
> 
> https://github.com/yihong0618/GitHubPoster/blob/248d0c8f998e75d1c9d198c47230f40ec2975b3c/github_poster/loader/from_github_issue_loader.py#L40-L45

成功了，谢谢。

**Comment by yihong0618** [comment]
客气了，可以关掉这个 issue 么？
感兴趣的话欢迎提个 PR 增加这块的说明。

**Comment by goldenages1989** [comment]
可以关掉了，已提PR

**Comment by yihong0618** [comment]
感谢。
