### ISSUE TITLE
Can not get weread hisoty data

### ISSUE THREAD

**Issue by zhiqli** [yihong0618/GitHubPoster#53]
微信读书的返回错误了，后去cookie的时候手机上显示登录成功，但是网页上二维码没有跳转，是否和这个有关系？

**Comment by yihong0618** [comment]
你先在网页登陆，得确定登陆成功了，再取 cookie

**Comment by zhiqli** [comment]
可以了，一开始扫的是readme里面提供的那个开放平台的二维码取到的cookie找不到数据。

**Comment by zhiqli** [comment]
谢谢yihong大哥，非常酷的项目。

**Comment by yihong0618** [comment]
好的。
