### ISSUE TITLE
run Push nes svg 时错误：Stderr:       | fatal: pathspec 'examples' did not match any files

### ISSUE THREAD

**Issue by lesnolie** [yihong0618/GitHubPoster#54]
![image](https://user-images.githubusercontent.com/81410185/153750126-1db73cea-c3d5-464e-8416-2710944572a5.png)
您好~我是程序小白，在执行ACTION的时候发生了这种错误。
但是我在OUT_FOLDER里面出现了仅仅1个SVG。

**Comment by lesnolie** [comment]
![image](https://user-images.githubusercontent.com/81410185/153750349-ce7e2d95-a86b-4d83-9434-8015f0e4f644.png)
再次运行出现这种情况

**Comment by lesnolie** [comment]
![1644750690(1)](https://user-images.githubusercontent.com/81410185/153750427-866924a5-8991-4edc-86c6-b4683fe9fca4.png)
另外我想问一下这一个API如何获取呢？我按照谷歌的方法得到如下结果：
![image](https://user-images.githubusercontent.com/81410185/153750419-df5462a1-eac1-4d02-b238-f0eba7d0b2c1.png)

期待您的回复，万分感谢

**Comment by yihong0618** [comment]
我明天帮你看下哈，今天有事儿可能没法开电脑

**Comment by lesnolie** [comment]
> 我明天帮你看下哈，今天有事儿可能没法开电脑

感谢您。
在推特偶然看见的您，对您使用github记录让我十分感兴趣以及惊讶。对您转行程序员也是十分的赞叹与敬佩。
现如今也使用了您的gitblog和用issue记录生活。
我是程序小白，上学时倒是挺想读软件或者计算机，但无奈受家人影响读了其他。现如今年纪大了，30多了，可接触这些让我感觉也十分有意思。
希望您不会嫌弃我的问题比较白痴。
祝周末愉快

**Comment by yihong0618** [comment]
> ![image](https://user-images.githubusercontent.com/81410185/153750349-ce7e2d95-a86b-4d83-9434-8015f0e4f644.png) 再次运行出现这种情况

你需要建一个 OUT_FOLDER 的空文件夹，你这个项目里是没有的。

**Comment by lesnolie** [comment]
原来如此，原来要用git add OUT_FOLDER/.gitkeep来强制上传空文件夹。感谢

**Comment by yihong0618** [comment]
@lesnolie 
我关掉了哈？ 如果有问题随时 reopen

**Comment by lesnolie** [comment]
> @lesnolie 我关掉了哈？ 如果有问题随时 reopen

你好，想问一下为什么EXAMPLES和OUT_FOLDER都没有新的NEW POSTER，但是运行程序时成功的。

**Comment by lesnolie** [comment]
> 因为没用这俩文件夹生成的时候

原来是yml里面忘记改type了，感谢感谢
