### ISSUE TITLE
bilibili时间只有三个月

### ISSUE THREAD

**Issue by zjgcjy** [yihong0618/GitHubPoster#61]
![image](https://user-images.githubusercontent.com/27962618/165885459-dd8d1966-a06d-4341-9c8b-38d9087b35fb.png)

看了一下应该不是脚本的问题，b站的历史纪录只支持记录最近三个月的，就提个issue建议说明一下哈，我以为是我搞错了。

**Comment by yihong0618** [comment]
之前好像支持更久的。
一个小方式，你可以 DIY 一下把之前的数据存起来～

**Comment by yihong0618** [comment]
先关了哈这个。
