### ISSUE TITLE
不懂就问，readme 里面两个 安装的区别是啥？

### ISSUE THREAD

**Issue by sanbeichahegongheguo** [yihong0618/GitHubPoster#62]
pip 安装
pip3 install -U 'github_poster[all]'
安装 (Python3.6+)
pip3 install -r requirements.txt

这两个安装不都是 pip 安装。是第一个安装方法 适用于 Python3.6 一下版本？

**Comment by yihong0618** [comment]
其实都行。推荐第一种，但你要提 PR 改代码的话第二种好些。
