### ISSUE TITLE
咨询，是否有参数可以控制生成的skyline 3D模型 的倒角

### ISSUE THREAD

**Issue by hanchengxu** [yihong0618/GitHubPoster#63]
发现生成的3D模型是带倒角的，github的skyline完全是直角。
想问问 有参数可以控制吗。 增加倒角是为了打印考虑的吗。

代码是master分支，commit id:97378e0e360d967c1729d15d6a4235e465d8e2ba

![キャプチャ](https://user-images.githubusercontent.com/19605200/173504178-39b01c6b-9bc4-4800-8d2c-0d063e45fff9.PNG)

**Comment by yihong0618** [comment]
应该没有，我用的是 https://github.com/fogleman/sdf 这个项目，fork 出来发的 pypi 这个自动带倒角了，可能需要改源码。

**Comment by yihong0618** [comment]
@hanchengxu 
我 fork 的地址，因为需要发布 PyPI 所以 fork 了一份。
https://github.com/yihong0618/sdf
