### ISSUE TITLE
Consider putting multiple resources into one single heatmap?

### ISSUE THREAD

**Issue by laixintao** [yihong0618/GitHubPoster#7]
This picture is from douban, which put books, movies and music into one single heatmap with different colors.

![IMAGE 2021-06-11 10:00:08](https://user-images.githubusercontent.com/9675939/121619828-ce035a80-ca9b-11eb-8832-76912ea9c094.jpg)

So I am thinking that we can put twitter, github, leetcode into one heatmap like this, then from the colors, you would get an idea about where does your time spend on.

**Comment by yihong0618** [comment]
Cool.

I'll try to see if I can achieve it, later~

**Comment by yihong0618** [comment]
@laixintao 

Seems max() resources support up to 3 maybe better.

**Comment by yihong0618** [comment]
Done.
![image](https://user-images.githubusercontent.com/15976103/125755668-5dc02d43-3c34-45f0-bff7-d83388ee6b0c.png)
