### ISSUE TITLE
运行命令后没有生成对应的SVG文件

### ISSUE THREAD

**Issue by guaguaguaxia** [yihong0618/GitHubPoster#72]
如题，照着README写的运行后在OUT_FOLDER下没有生成SVG文件，没有报错信息，控制台无任何输出。请问有什么可提供的排查思路吗

**Comment by yihong0618** [comment]
@guaguaguaxia 能来个截图么？

**Comment by guaguaguaxia** [comment]
![image](https://user-images.githubusercontent.com/18466048/210344683-a33a4aa7-f989-4688-a239-d9ce98b3799f.png)

**Comment by yihong0618** [comment]
加个 --year 2022 试试？

**Comment by guaguaguaxia** [comment]
![image](https://user-images.githubusercontent.com/18466048/210350812-410edb2a-af0f-457a-9482-3549e8e7b228.png)

还是一样的结果。在D:\PythonProject\GitHubPoster\OUT_FOLDER下检查了没有SVG文件生成。需要我提供更多信息吗

**Comment by yihong0618** [comment]
有点奇怪，你试试 github 的

```
python3 -m github_poster github --github_user_name guaguaguaxia --me guaguaguaxia --year 2019-2022
```

**Comment by guaguaguaxia** [comment]
还是一样不行。这个问题应该是我本地环境问题，或者其它偶然情况下触发的bug。我这两天有时间clone代码看下，有进度会更新在这个issue下。感谢repo owner

**Comment by yihong0618** [comment]
嗯嗯，
debug 

1. 试试单独打 python3 看看有没有
2.  python3 -m __hello__ 看看能不能打出来 hello world
3. 如果前两项能的话 试试 pip 安装 github_poster 然后用 pip 版本
4. 可以装一个 wsl 看看
5. 可以用 GitHub Actions

**Comment by guaguaguaxia** [comment]
没有python3......，环境变量的python命令。谢谢，关issue了
