### ISSUE TITLE
An error occurred generating github svg

### ISSUE THREAD

**Issue by liqun98** [yihong0618/GitHubPoster#75]
fork仓库之后试用一下Actions，发现github的svg生成跑不通，看了一下您这边的源仓库，从2023年开始的Schedule Actions也没跑通，报错的代码片段如下
<img width="801" alt="截屏2023-01-08 18 58 30" src="https://user-images.githubusercontent.com/71168966/211192411-7e323769-29aa-4f63-bb81-f7a9f9b2a1a7.png">

进一步发现years为空，导致years为空的是reduce_year_list函数，这个函数将years数组缩减为从非0的年份开始，但是实际从github拿到的数据又全部为0，怀疑是github调整了contribution面板的rect属性，导致没有拿到正确的数据

修改了github_parser，提交了一个PR，因为我不常用Python，所以有些语法可能不够优雅，还希望您耐心review我的代码

**Comment by yihong0618** [comment]
感谢。我看看
