### ISSUE TITLE
多邻国登陆接口挂掉了?

### ISSUE THREAD

**Issue by malinkang** [yihong0618/GitHubPoster#94]
多邻国一直报错，打印了下登录接口的返回值，返回的是html。是接口挂了？还是我账号的问题？
![image](https://user-images.githubusercontent.com/3365208/232729376-c348fe80-4067-4a44-9042-a09bcbc41043.png)

**Comment by yihong0618** [comment]
我们今晚看一下

**Comment by yihong0618** [comment]
@malinkang 确认挂了。。。我想想办法。。。

**Comment by yihong0618** [comment]
@malinkang better
